apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tekton-flux-demo-manifest
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/mhussain78/tekton-flux-demo-manifest.git