apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tekton-flux-demo-manifest
  namespace: default
spec:
  interval: 15m
  path: "./flux"
  prune: true
  sourceRef:
    kind: GitRepository
    name: tekton-flux-demo-manifest